# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='images'),
        ),
    ]
